### ISSUE TITLE
Combination with Term.jl to show the output much better.

### ISSUE THREAD

**Issue by shayandavoodii** [peng1999/DepTree.jl#1]
Hi, I got familiar with this excellent work couple of minutes ago. I imagined the combination of this module with [`Term.jl`](https://github.com/FedeClaudi/Term.jl) would be great to show the output of `PkgDependencies.tree()` in a much more delightful way. This is a requested feature, and I would be happy if you mind it.

**Comment by peng1999** [comment]
Thank for your recommendation of `Term.jl`! I'm experimenting this but found it cannot display tree in a specific order currently. I should wait for FedeClaudi/Term.jl#139 to be solved.

**Comment by shayandavoodii** [comment]
> Thank for your recommendation of `Term.jl`! I'm experimenting this but found it cannot display tree in a specific order currently. I should wait for [FedeClaudi/Term.jl#139](https://github.com/FedeClaudi/Term.jl/issues/139) to be solved.

Hi,
I see. I look forward to the good news!

**Comment by shayandavoodii** [comment]
After update the `Term.jl` to `v1.0.4`, the `PkgDependency` automatically downgraded to `0.1.0`.
