### ISSUE TITLE
Show full tree

### ISSUE THREAD

**Issue by aplavin** [peng1999/DepTree.jl#10]
Would be useful to optically display the whole tree, without collapsing packages already encountered above. Helpful for visually evaluating how heavy each dependency is.

**Comment by peng1999** [comment]
If we do not cut the duplicated trees, the whole tree to display may become unreasonably large, or even cannot stop if we have loop dependencies.

There's serveral ways I can think of to tackle this:
1. Add `maxdepth` option and require it if `whole_tree=true` is presented.
2. Output dot file or SVG of dependency graph. Anyway essentially dependency is more like a graph than a tree.
3. Make a TUI and enable uses to expand subtrees at will.

@aplavin Does any of the above method suits your need?

**Comment by aplavin** [comment]
I personally don't want any interactivity, the current display format is nice. For now, I just use a fork with this condition https://github.com/peng1999/PkgDependency.jl/blob/b77ebb435a6e76bf7de35b570dfc43b354f557c3/src/PkgDependency.jl#L112 removed. Would be ideal to be able to show the full tree, but repeated entries in a different color.

> or even cannot stop if we have loop dependencies.

Is that possible at all? How can A depend on B and B depend on A?

> Add maxdepth option and require it if whole_tree=true is presented.

For me, maxdepth=Inf would be best!
Do you have any actual example with extremely long/deep dependency trees, that are infeasible to print when a user passes whole_tree=true?

**Comment by peng1999** [comment]
`dedup=false` option is added in 57d4d93
