### ISSUE TITLE
Consider installing package if not already

### ISSUE THREAD

**Issue by juliohm** [peng1999/DepTree.jl#4]
Right now if the user types `PkgDependency.tree("Foo" )` and Foo is not available in the environment we get a bad error message. It would be nice to prompt the user to install the package or maybe create a temporary environment always behind the scenes where the package is added and the tree is built.

**Comment by peng1999** [comment]
Thanks for the feedback! A custom exception will be threw after 99c116e.

**Comment by juliohm** [comment]
Thank you for the error message!
